### ISSUE TITLE
Waves Auth API Page: Demo link is broken

### ISSUE THREAD

**Issue by sunchaser68** [wavesplatform/waves-documentation#1403]
In WAVES Auth Page:
[https://docs.wavesplatform.com/en/waves-api-and-sdk/client-api/auth-api.html](https://docs.wavesplatform.com/en/waves-api-and-sdk/client-api/auth-api.html)

The _Here_ link is broken in the following sentence:

Due to the length limitations of the query string all parameters are expressed with one character.
**Here** you can find the demo project which shows how to use Web auth API.

**Comment by mialkin** [comment]
Hi!

Thank you very much for your feedback! 

The link is indeed broken and not relevant anymore. We removed it from the page (page needs to be hard refreshed to see the difference).
