### ISSUE TITLE
Is RIDE example wrong?

### ISSUE THREAD

**Issue by sunchaser68** [wavesplatform/waves-documentation#1426]
In section Smart Contracts -> Ride-Apps there is a code example of a call to a deposit function with args type:integer, value: 6000000000.

```
[...]
{
  "type": 16,
  "version": 1,
  "senderPublicKey": "2GEvUnpNpve2rSAs51c2HMTkaCYW9QRgwR16Z2HGJZgC",
  "dappAddress": "3FYR1f5YydHXF8dtfRJRyX3PoDCoT7a36Kq",
  "call": {
    "function": "deposit",
    "args": [{type:"integer", value: 600000000}]
  },
  "payment": [
 [...]
```

But in the RIDE contract we see:

```
[...]
# Callable function that accepts payments from other accounts and deposits them to the account to which the dApp is attached to.
@Callable(i)        # Context object with the name "i".
func deposit() = {
   let pmt = extract(i.payment)
   if (isDefined(pmt.assetId)) then throw("can hold waves only at the moment")
   else {
        let currentKey = toBase58String(i.caller.bytes)
        let currentAmount = match getInteger(this, currentKey) {
            case a:Int => a
            case _ => 0
[...]
```

Should not the func deposit () have a parameter?

**Comment by mrkraft** [comment]
No. 
The code example had an error. We fixed it.

Thx.

**Comment by mialkin** [comment]
@sunchaser68 Thank you a lot for your contribution! Feel free to let us know in case of any problems.

**Comment by sunchaser68** [comment]
Sure @mialkin  do you prefer I open issues or i try to fix them with a Pull Request?

**Comment by mialkin** [comment]
Go ahead and do pull requests if it's more convenient for you. If there will be any questions we will discuss.
