### ISSUE TITLE
Check and fix the links after move files to another folders.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/waves-documentation#1529]
Some links, not working. Example: https://github.com/wavesplatform/waves-documentation/blob/master/en/blockchain/node/mining-node.md

**Comment by mialkin** [comment]
Yes, our internal links do not work inside of GitHub.

Please check the links on our website https://docs.wavesplatform.com/en/blockchain/node/mining-node.html. They are working there.

**Comment by username1565** [comment]
Ok. I see relative pathways, and this because `/tree/master/` changed to `/blob/master` on github.
Issue is closed.
