### ISSUE TITLE
Curve25519 for PHP

### ISSUE THREAD

**Issue by deemru** [wavesplatform/waves-documentation#269]
Feel free to add to your [Cryptographic Practical Details](https://docs.wavesplatform.com/en/technical-details/cryptographic-practical-details.html) a port of Curve25519 sign/verify for PHP: https://github.com/deemru/w8io/blob/master/include/w8io_25519.php

**Comment by KardanovIR** [comment]
@deemru thank you for your contribution!
Can you create a separate repo for the file, please?

**Comment by deemru** [comment]
done: https://github.com/deemru/curve25519-php
