### ISSUE TITLE
Update Joining Testnet page

### ISSUE THREAD

**Issue by KardanovIR** [wavesplatform/waves-documentation#384]
Information about joining testnet on the page (https://docs.wavesplatform.com/en/waves-full-node/joining-testnet.html) is outdated. 
The latest version of docker container is here: https://github.com/wavesplatform/node-docker-image

**Comment by KardanovIR** [comment]
@Nazeim Fix this issue ASAP, please.

**Comment by Nazeim** [comment]
@KardanovIR 
done
