### ISSUE TITLE
Change style of inline codes 

### ISSUE THREAD

**Issue by KardanovIR** [wavesplatform/waves-documentation#583]
Inline codes (` wrapped text) in current version look very bad, let's make sexier with new styling and button to copy to clipboard. 
An example is here: https://docs.sonm.com/installation/install-form-deb-packages

![image](https://user-images.githubusercontent.com/1945126/48853741-3b0d5280-edc1-11e8-92cb-a9ccb050fbbb.png)

**Comment by Nazeim** [comment]
Done
