### ISSUE TITLE
empty document for rest api public functions

### ISSUE THREAD

**Issue by sabotagebeats** [wavesplatform/waves-documentation#753]
this is empty, I'm assuming should have some info? 

https://github.com/wavesplatform/waves-documentation/blob/master/en/waves-node-rest-api/public-functions.md

**Comment by sabotagebeats** [comment]
hmm looks like they're all empty except "private functions"

https://github.com/wavesplatform/waves-documentation/tree/master/en/waves-node-rest-api

**Comment by sabotagebeats** [comment]
i see it looks like they're available here. 
https://github.com/wavesplatform/waves-documentation/tree/master/en/development-and-api/waves-node-rest-api
original branch should be removed?

**Comment by sabotagebeats** [comment]
fixed here: 
https://github.com/wavesplatform/waves-documentation/pull/754
https://github.com/wavesplatform/waves-documentation/pull/755
https://github.com/wavesplatform/waves-documentation/pull/756
https://github.com/wavesplatform/waves-documentation/pull/757
https://github.com/wavesplatform/waves-documentation/pull/758
https://github.com/wavesplatform/waves-documentation/pull/759

**Comment by Nazeim** [comment]
Thanks for fixing.
all reviewed and merged
